#!/bin/bash
# session-summary.sh - Stop Hook (with dedup)
# Generates concise session index entries for later retrieval
# Each session recorded only once, deduped by session_id
#
# Output file: configurable via CC_SESSION_INDEX or default path
# Purpose: Quick index for searching past sessions and weekly summaries

# === Hook Profile control (inspired by ECC) ===
[ "${CC_HOOK_PROFILE:-standard}" = "off" ] && exit 0
case ",${CC_DISABLED_HOOKS}," in *",$(basename "$0"),"*) exit 0 ;; esac

# === CUSTOMIZE THIS ===
INDEX_FILE="${CC_SESSION_INDEX:-$HOME/.claude/session-index.md}"

# Read stdin
INPUT=$(cat)

# Extract session_id
SESSION_ID=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('session_id','unknown'))" 2>/dev/null || echo "unknown")

# Dedup: skip if already recorded
if [ -f "$INDEX_FILE" ] && grep -q "$SESSION_ID" "$INDEX_FILE" 2>/dev/null; then
  exit 0
fi

# Extract transcript_path
TRANSCRIPT=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('transcript_path',''))" 2>/dev/null || echo "")

# Pass to Python via export
export TRANSCRIPT_PATH="$TRANSCRIPT"

# Extract concise summary
SUMMARY=$(python3 << 'PYEOF'
import json, sys, os, re

transcript = os.environ.get("TRANSCRIPT_PATH", "")
if not transcript or not os.path.exists(transcript):
    print("(new session)")
    sys.exit(0)

user_msgs = []
tools_used = set()

with open(transcript) as f:
    for line in f:
        try:
            entry = json.loads(line.strip())
            etype = entry.get("type", "")

            if etype == "user":
                content = entry.get("message", {}).get("content", "")
                if isinstance(content, list):
                    content = " ".join(c.get("text", "") for c in content if isinstance(c, dict) and c.get("type") == "text")
                if isinstance(content, str):
                    # Filter system noise
                    clean = re.sub(r'<[^>]+>.*?</[^>]+>', '', content, flags=re.DOTALL).strip()
                    # Filter pure task-notification, system-reminder
                    if clean and not clean.startswith('<') and len(clean) > 3:
                        user_msgs.append(clean.replace("\n", " "))

            if etype == "assistant":
                msg = entry.get("message", {})
                content = msg.get("content", [])
                if isinstance(content, list):
                    for block in content:
                        if isinstance(block, dict) and block.get("type") == "tool_use":
                            name = block.get("name", "")
                            if name and not name.startswith("mcp__"):
                                tools_used.add(name)
        except:
            pass

# Generate one-line summary
if not user_msgs:
    print("(empty session)")
    sys.exit(0)

# Topic = first user message (truncated to 60 chars)
topic = user_msgs[0][:60]

# Extract key action words from subsequent messages (deduped, skip short ones)
actions = []
seen = set()
for msg in user_msgs[1:]:
    if len(msg) < 5:
        continue
    short = msg[:30]
    if short in seen:
        continue
    seen.add(short)
    actions.append(msg[:50])
    if len(actions) >= 5:
        break

# Output
turns = len(user_msgs)
tools_str = ", ".join(sorted(tools_used)[:6])

print(f"**Topic**: {topic}")
if actions:
    print(f"**Actions**: {'; '.join(actions)}")
print(f"**Turns**: {turns} | **Tools**: {tools_str if tools_str else 'conversation'}")
PYEOF
)

# Create index file if not exists
if [ ! -f "$INDEX_FILE" ]; then
  mkdir -p "$(dirname "$INDEX_FILE")"
  cat > "$INDEX_FILE" << 'HEADER'
# Session Index

> Auto-generated by session-summary.sh hook
> Format: date | session-id -> topic + actions + tools

HEADER
fi

TIMESTAMP=$(date "+%m-%d %H:%M")

cat >> "$INDEX_FILE" << EOF

---
$TIMESTAMP | \`$SESSION_ID\`
$SUMMARY
EOF

# === Learning hint: detect error->fix patterns ===
# Lightweight version of ECC pattern extraction
if [ -n "$TRANSCRIPT" ] && [ -f "$TRANSCRIPT" ]; then
  LEARNING_HINT=$(python3 << 'LEARNEOF'
import json, os, re

transcript = os.environ.get("TRANSCRIPT_PATH", "")
if not transcript or not os.path.exists(transcript):
    exit(0)

has_error_fix = False
has_remember = False
error_context = ""

prev_had_error = False
with open(transcript) as f:
    for line in f:
        try:
            entry = json.loads(line.strip())
            etype = entry.get("type", "")

            if etype == "user":
                content = entry.get("message", {}).get("content", "")
                if isinstance(content, list):
                    content = " ".join(c.get("text", "") for c in content if isinstance(c, dict))
                if isinstance(content, str):
                    if re.search(r'(remember|note this|don.t forget|next time)', content, re.I):
                        has_remember = True

            if etype == "assistant":
                msg = entry.get("message", {})
                content = msg.get("content", [])
                if isinstance(content, list):
                    for block in content:
                        if isinstance(block, dict):
                            text = block.get("text", "")
                            if re.search(r'(error|failed|Error)', text):
                                prev_had_error = True
                                error_context = text[:80]
                            elif prev_had_error and block.get("type") == "tool_use":
                                if block.get("name") in ("Edit", "Write", "Bash"):
                                    has_error_fix = True
                                    prev_had_error = False
        except:
            pass

hints = []
if has_error_fix:
    hints.append(f"error->fix pattern: {error_context}")
if has_remember:
    hints.append("user said 'remember/note this'")

if hints:
    print(" | ".join(hints))
LEARNEOF
  )

  if [ -n "$LEARNING_HINT" ]; then
    echo "[learning-hint] Consider saving to learnings: $LEARNING_HINT" >&2
  fi
fi

exit 0
